def build_react_prompt(ir_json: str) -> str:
    return (
        "You are a senior React/TypeScript engineer. Convert the IRBundle JSON below into a\n"
        "single complete App.tsx file using Ant Design. Every instruction below is mandatory.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " OUTPUT RULES\n"
        "═══════════════════════════════════════════════\n"
        "- Output ONLY raw TSX — no markdown fences, no prose, no comments outside code.\n"
        "- Export default function `GeneratedApp()`. No return type annotation.\n"
        "- No default React import. Named imports only: import { useState, useMemo, useEffect, useCallback } from 'react'.\n"
        "- Only import Ant Design components you actually use in JSX. Never import unused components.\n"
        "- No `any` type anywhere. Derive types from IR state/entity definitions or use explicit interfaces.\n"
        "- Code must compile with zero errors under strict TypeScript (`tsc -b`).\n"
        "- Do not add placeholder comments like '// TODO' or '// Add logic here'.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " NOTIFICATIONS\n"
        "═══════════════════════════════════════════════\n"
        "- Always use: const [messageApi, contextHolder] = message.useMessage();\n"
        "- Render {contextHolder} as the first child inside ConfigProvider.\n"
        "- Never use App.message or notification directly.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " THEME — wire from IR, never hardcode\n"
        "═══════════════════════════════════════════════\n"
        "- Read component_ir.theme and apply EXACTLY those values to ConfigProvider:\n"
        "    <ConfigProvider theme={{ token: { colorPrimary: '<IR primaryColor>', borderRadius: <IR borderRadius>, fontFamily: '<IR fontFamily>' }, algorithm: theme.defaultAlgorithm }}>\n"
        "- Never hardcode colors like '#1890ff'. Always use the actual values from component_ir.theme.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " FULLSCREEN LAYOUT — mandatory\n"
        "═══════════════════════════════════════════════\n"
        "- The root div MUST have BOTH of these — no exceptions:\n"
        "    minHeight: '100vh'   <- REQUIRED. Guarantees full viewport height even if CSS chain is broken.\n"
        "    height: '100%'       <- REQUIRED. Fills parent when html/body/#root have height:100%.\n"
        "  Full required style: style={{ minHeight: '100vh', height: '100%', width: '100%', display: 'flex', flexDirection: 'column' }}\n"
        "  WRONG: style={{ height: '100%', ... }}          <- missing minHeight, causes empty space\n"
        "  WRONG: style={{ minHeight: '100vh', ... }}      <- missing height, does not fill parent\n"
        "- Action buttons that belong to a section MUST be placed INSIDE their parent Card/section,\n"
        "  not in a separate div after the closing Card tag. A Calculate or Submit button belongs\n"
        "  inside the Card that contains the form/table it acts on, at the bottom of that Card.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " STATE — derived strictly from IR\n"
        "═══════════════════════════════════════════════\n"
        "- Declare one useState per entry in data_ir.state. Map IR types to TypeScript:\n"
        "    string->string, number->number, boolean->boolean, array->TypedArray[], object->interface, enum->string literal union.\n"
        "- Never invent state variables not in data_ir.state.\n"
        "- For each entity in data_model_ir.entities, declare a TypeScript interface above the component.\n"
        "  Use the entity's fields as properties (string by default; field names with 'id'/'count'/'amount'/'score'->number; 'active'/'enabled'->boolean).\n"
        "- Wrap data_ir.derived values in useMemo. Wrap stable column definitions in useMemo too.\n"
        "- When state represents a list of similar entities (students, products, rows), ALWAYS use\n"
        "  a single useState<EntityType[]>([...]) array — NEVER declare flat per-item state variables\n"
        "  like student1Math, student2Math, student3Math. Flat state does not scale and causes\n"
        "  massive dependency arrays and unused setters.\n"
        "  WRONG: const [student1Math, setStudent1Math] = useState<number|null>(null)  <- never do this\n"
        "  CORRECT: const [students, setStudents] = useState<Student[]>([...])\n"
        "  Update a single item: setStudents(prev => prev.map((s,i) => i===idx ? {...s, math: val} : s))\n"
        "- TypeScript interfaces defined above the component MUST be used to type state variables.\n"
        "  If you declare interface Student, you MUST use useState<Student[]> somewhere.\n"
        "  Never declare an interface and leave it unused — this is a TS error.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " EVENT HANDLERS — derived strictly from IR\n"
        "═══════════════════════════════════════════════\n"
        "- Implement one handler per entry in behaviour_ir.events and behaviour_ir.actions.\n"
        "- Name handlers after their event/action ID (camelCase).\n"
        "- For actions with validation_rules: check each rule first, show messageApi.error on failure.\n"
        "- For actions with side_effects, run each after state updates:\n"
        "    toast -> messageApi.success/error/info per config.type\n"
        "    modal_open/close -> set modal trigger_state true/false\n"
        "    drawer_open/close -> set drawer trigger_state true/false\n"
        "    reset_state -> reset config.fields to their data_ir.state initial values\n"
        "    navigate -> window.location.href = config.path\n"
        "- For actions with requires_confirmation: wrap in Modal.confirm().\n"
        "- Never invent handlers. Never leave handler bodies empty.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " FORMS — use Antd Form correctly\n"
        "═══════════════════════════════════════════════\n"
        "- Always: const [form] = Form.useForm(). Pass to component: <Form form={form}>.\n"
        "- On open: call form.resetFields() or form.setFieldsValue().\n"
        "- On submit: call form.validateFields() — do NOT use a parallel formData state object.\n"
        "- Add rules={[{ required: true }]} to fields where data_ir.state[*].required is true.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " NAVIGATION — wire from navigation_ir\n"
        "═══════════════════════════════════════════════\n"
        "- navigation_ir.tabs non-empty: render Antd Tabs. Map each TabDef to { key, label, children }.\n"
        "  Use navigation_ir.default_tab or first tab as default active key.\n"
        "  Never invent hardcoded menu items not in the IR.\n"
        "- navigation_ir.modals non-empty: render one Modal per ModalDef.\n"
        "  open={state[modal.trigger_state]}, onCancel sets it false + form.resetFields().\n"
        "  Footer buttons map modal.footer_actions to Button components.\n"
        "- navigation_ir.drawers non-empty: render one Drawer per DrawerDef.\n"
        "  open={state[drawer.trigger_state]}, onClose sets it false.\n"
        "- Render Modals and Drawers as direct children of ConfigProvider, NOT inside Layout.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " LAYOUT — map layout_ir to CSS\n"
        "═══════════════════════════════════════════════\n"
        "Root div: minHeight:'100vh', height:'100%', width:'100%', display:'flex', flexDirection:'column'.\n"
        "\n"
        "Map layout_ir.layout[id].type:\n"
        "  vertical   -> display:'flex', flexDirection:'column'\n"
        "  horizontal -> display:'flex', flexDirection:'row', flexWrap:'wrap'\n"
        "  grid       -> display:'grid', gridTemplateColumns:'repeat(N,1fr)'  (N=layout.columns)\n"
        "  sidebar    -> display:'grid', gridTemplateColumns: layout.column_template or '280px 1fr'\n"
        "  stack      -> position:'relative'  (children: position:'absolute')\n"
        "\n"
        "Apply layout_ir.layout[id].gap as CSS gap property.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " DATA FETCHING — wire from data_fetch_ir\n"
        "═══════════════════════════════════════════════\n"
        "- on_mount trigger: generate useEffect with fetch(endpoint.url).\n"
        "- manual trigger: generate a named handler function with fetch(endpoint.url).\n"
        "- Wire loading_state_key and error_state_key to the corresponding IR state vars.\n"
        "- On fetch error: messageApi.error + render an Antd Alert in JSX (not just toast).\n"
        "- If data_fetch_ir is empty: do not generate any fetch logic.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " TABLES\n"
        "═══════════════════════════════════════════════\n"
        "- Wrap column definitions in useMemo.\n"
        "- Derive rowKey from data_model_ir entity's 'id' field if present, else first field.\n"
        "- If no entity rowKey is available: rowKey={(_, i) => String(i)}.\n"
        "- Table dataSource MUST contain plain data values only — never JSX elements.\n"
        "  WRONG: { name: <Text>{val}</Text>, math: <InputNumber .../> }  <- JSX in data\n"
        "  CORRECT: { name: val, math: numVal } with column.render() for display logic:\n"
        "    { title: 'Math', dataIndex: 'math', render: (_, record, i) =>\n"
        "        <InputNumber value={record.math} onChange={val => updateStudent(i, 'math', val)} /> }\n"
        "- Never store setter functions or onChange handlers directly inside dataSource objects.\n"
        "- CSSProperties fontWeight must be a NUMBER not a string: fontWeight: 600 not fontWeight: '600'.\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " COMPONENT BINDING\n"
        "═══════════════════════════════════════════════\n"
        "- component.label    -> children or title prop\n"
        "- component.bind     -> value prop (controlled), wired to the named state variable\n"
        "- component.onClick  -> onClick prop wired to the named handler\n"
        "- component.styles   -> style prop as CSSProperties\n"
        "- component.visible_when  -> conditional: {expr ? <Comp/> : null}\n"
        "- component.disabled_when -> disabled prop\n"
        "\n"
        "═══════════════════════════════════════════════\n"
        " IRBundle JSON:\n"
        "═══════════════════════════════════════════════\n"
        + ir_json
    )